In [1]:
import numpy as np
import tensorflow as tf

In [4]:
a = np.array([
    [2.1, 3.1, 3.9],
    [3.2, 4.5, 3.1]
])

In [5]:
print(a)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]


In [6]:
print(a.shape)

(2, 3)


In [7]:
np.mean(a, axis=1)

array([3.03333333, 3.6       ])

In [8]:
a+3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

In [ ]:
# 여기까지가 간단한 넘파이 어레이

In [9]:
import tensorflow as tf

In [14]:
with tf.name_scope('abc'):
    a= tf.constant(3, dtype=tf.float32, name = 'const')

print(a)

Tensor("abc/const:0", shape=(), dtype=float32)


In [21]:
# value 출력
with tf.Session() as sess:
    print(sess.run(a))

3.0


In [23]:

a= tf.constant(3, dtype=tf.float32, name = 'const')
b= tf.Variable(0, dtype=tf.float32)
c= a+b
print(a)
print(b)

init = tf.global_variables_initializer()

Tensor("const_8:0", shape=(), dtype=float32)
<tf.Variable 'Variable_3:0' shape=() dtype=float32_ref>


In [28]:
# b= a+b 를 돌리면 처음에 b 는 0, 3, 6 ~~으로 계속 증가
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))
    print(sess.run(b))

3.0
0.0


In [ ]:
# 그래프를 돌리는 행위를 세션 안에서 하면 안된다!

In [29]:
a= tf.constant(3, dtype=tf.float32, name = 'const')
b= tf.Variable(0, dtype=tf.float32)
b= a+b
print(a)
print(b)

init = tf.global_variables_initializer()

Tensor("const_9:0", shape=(), dtype=float32)
Tensor("add_4:0", shape=(), dtype=float32)


In [30]:
# b= a+b 를 돌리면 처음에 b 는 0, 3, 6 ~~으로 계속 증가
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(b))
    print(sess.run(b))

3.0
3.0


In [31]:
a= tf.constant(3, dtype=tf.float32, name = 'const')
b= tf.Variable(0, dtype=tf.float32)
c= tf.assign(b, a+b)
print(a)
print(b)

init = tf.global_variables_initializer()

Tensor("const_10:0", shape=(), dtype=float32)
<tf.Variable 'Variable_5:0' shape=() dtype=float32_ref>


In [32]:
# b= a+b 를 돌리면 처음에 b 는 0, 3, 6 ~~으로 계속 증가
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))
    print(sess.run(c))

3.0
6.0


In [33]:
a= tf.constant(3, dtype=tf.float32, name = 'const')
b= tf.Variable(0, dtype=tf.float32)
c= tf.assign(a, a+a)
print(a)
print(b)

init = tf.global_variables_initializer()

AttributeError: 'Tensor' object has no attribute 'assign'

In [ ]:
# 콘스탄트는 값이 바뀔수가 없어서 에러가 발생하는것

In [34]:
a= tf.constant(3, dtype=tf.float32, name = 'const')
b= tf.Variable(0, dtype=tf.float32)
print(a)
a= a+a
print(a)

init = tf.global_variables_initializer()

Tensor("const_12:0", shape=(), dtype=float32)
Tensor("add_7:0", shape=(), dtype=float32)


In [ ]:
# 프린트를 한것을 보면 a 의 정의가 2가지, 콘스탄트, add 두개로 존재한다 즉 두 값은 같지 않은것!
# 따라서 값이 바뀔수 있는 베리어블을 선언해주어야 한다. (텐서에서는 계속해서 베리어블을 선언해주어야한다. 하지만 요센 계속 선언하진 않음)

In [ ]:
--------------------------------------------------------------------------------------------------------------

In [40]:
np.random.seed(42)
x = tf.placeholder(tf.float32, shape=(), name = 'x')
y = tf.placeholder(tf.float32, shape=(), name = 'y')
w = tf.Variable(np.random.randn(), dtype=tf.float32)

a = tf.assign(w, w+x+y)

init = tf.global_variables_initializer()

In [41]:
with tf.Session() as sess:
    sess.run(init)
    
    for _ in range(0,10):
        print(sess.run(w))
        sess.run(a, feed_dict={x:1.0, y:2.0})
    print(sess.run(w))

0.49671414
3.496714
6.496714
9.496714
12.496714
15.496714
18.496714
21.496714
24.496714
27.496714
30.496714


In [ ]:
## placeholder vs Variable